/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tgm' at '19.04.17 08:16' with Gradle 2.14.1
 *
 * @author tgm, @date 19.04.17 08:16
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
